
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.doz_in_maincraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.doz_in_maincraft.item.UnfinishedStimulantItem;
import net.mcreator.doz_in_maincraft.item.TripleTearBloodItem;
import net.mcreator.doz_in_maincraft.item.TolkachItem;
import net.mcreator.doz_in_maincraft.item.TitaniumPlatesItem;
import net.mcreator.doz_in_maincraft.item.TinIngotItem;
import net.mcreator.doz_in_maincraft.item.TTSimbiotItem;
import net.mcreator.doz_in_maincraft.item.TTItem;
import net.mcreator.doz_in_maincraft.item.SymbioticUlcerItem;
import net.mcreator.doz_in_maincraft.item.SymbioticPiecesItem;
import net.mcreator.doz_in_maincraft.item.SurvivorsArmorItem;
import net.mcreator.doz_in_maincraft.item.SurvivorArmorSetItem;
import net.mcreator.doz_in_maincraft.item.StimulatorItem;
import net.mcreator.doz_in_maincraft.item.SteelPlateItem;
import net.mcreator.doz_in_maincraft.item.SteelBarrelItem;
import net.mcreator.doz_in_maincraft.item.StealSwordItem;
import net.mcreator.doz_in_maincraft.item.StealShovelItem;
import net.mcreator.doz_in_maincraft.item.StealPickaxeItem;
import net.mcreator.doz_in_maincraft.item.StealIngotItem;
import net.mcreator.doz_in_maincraft.item.StealHoeItem;
import net.mcreator.doz_in_maincraft.item.StealAxeItem;
import net.mcreator.doz_in_maincraft.item.StealArmorItem;
import net.mcreator.doz_in_maincraft.item.StabilizerStokerItem;
import net.mcreator.doz_in_maincraft.item.StabilizerGeminiItem;
import net.mcreator.doz_in_maincraft.item.StabilizerDiodeItem;
import net.mcreator.doz_in_maincraft.item.SpecialForcesCommunicatorItem;
import net.mcreator.doz_in_maincraft.item.SekretArmorItem;
import net.mcreator.doz_in_maincraft.item.SeedlingMagicPineItem;
import net.mcreator.doz_in_maincraft.item.ScarHfullItem;
import net.mcreator.doz_in_maincraft.item.ScarHItem;
import net.mcreator.doz_in_maincraft.item.ScarHAmmoItem;
import net.mcreator.doz_in_maincraft.item.SPAS12Item;
import net.mcreator.doz_in_maincraft.item.RevolverDrumItem;
import net.mcreator.doz_in_maincraft.item.RescueBeaconItem;
import net.mcreator.doz_in_maincraft.item.PressureRegulatorItem;
import net.mcreator.doz_in_maincraft.item.PrecisionToolItem;
import net.mcreator.doz_in_maincraft.item.PlateShapeItem;
import net.mcreator.doz_in_maincraft.item.PlasmaCableItem;
import net.mcreator.doz_in_maincraft.item.PieceTinItem;
import net.mcreator.doz_in_maincraft.item.PicklockItem;
import net.mcreator.doz_in_maincraft.item.Patron556Item;
import net.mcreator.doz_in_maincraft.item.Patron10mmItem;
import net.mcreator.doz_in_maincraft.item.PP19BizonItem;
import net.mcreator.doz_in_maincraft.item.P762atronItem;
import net.mcreator.doz_in_maincraft.item.NylonFabricItem;
import net.mcreator.doz_in_maincraft.item.NezeriteDustItem;
import net.mcreator.doz_in_maincraft.item.MoltenSteelItem;
import net.mcreator.doz_in_maincraft.item.MagnumItem;
import net.mcreator.doz_in_maincraft.item.MGLItem;
import net.mcreator.doz_in_maincraft.item.LoadForestersItem;
import net.mcreator.doz_in_maincraft.item.LeadIngotItem;
import net.mcreator.doz_in_maincraft.item.LargeBoxFromHozmagItem;
import net.mcreator.doz_in_maincraft.item.L96A1Item;
import net.mcreator.doz_in_maincraft.item.KevlarItem;
import net.mcreator.doz_in_maincraft.item.KarbonItem;
import net.mcreator.doz_in_maincraft.item.IronPlatesItem;
import net.mcreator.doz_in_maincraft.item.HugeBoxFromHozmagItem;
import net.mcreator.doz_in_maincraft.item.HealingMixtureItem;
import net.mcreator.doz_in_maincraft.item.Grenade40MmItem;
import net.mcreator.doz_in_maincraft.item.GasgasMaskItem;
import net.mcreator.doz_in_maincraft.item.GasMaskCrahetItem;
import net.mcreator.doz_in_maincraft.item.GasItem;
import net.mcreator.doz_in_maincraft.item.GasFilterItem;
import net.mcreator.doz_in_maincraft.item.FwwItem;
import net.mcreator.doz_in_maincraft.item.FortressArmorSetItem;
import net.mcreator.doz_in_maincraft.item.ForestersSpearItem;
import net.mcreator.doz_in_maincraft.item.FillerItem;
import net.mcreator.doz_in_maincraft.item.FLUEDGLASSItem;
import net.mcreator.doz_in_maincraft.item.ExecutionerHeartItem;
import net.mcreator.doz_in_maincraft.item.EmptyStimulantItem;
import net.mcreator.doz_in_maincraft.item.EmptyBalloonItem;
import net.mcreator.doz_in_maincraft.item.ElectricalTapeItem;
import net.mcreator.doz_in_maincraft.item.DrumShapeItem;
import net.mcreator.doz_in_maincraft.item.DoubleBloodyTearItem;
import net.mcreator.doz_in_maincraft.item.DfgdItem;
import net.mcreator.doz_in_maincraft.item.DetailSpecialAKMItem;
import net.mcreator.doz_in_maincraft.item.DetailSpas12Item;
import net.mcreator.doz_in_maincraft.item.DetailSkarHItem;
import net.mcreator.doz_in_maincraft.item.DetailSWDItem;
import net.mcreator.doz_in_maincraft.item.DetailPPHItem;
import net.mcreator.doz_in_maincraft.item.DetailPP19Item;
import net.mcreator.doz_in_maincraft.item.DetailPMItem;
import net.mcreator.doz_in_maincraft.item.DetailGausItem;
import net.mcreator.doz_in_maincraft.item.DetailAKMItem;
import net.mcreator.doz_in_maincraft.item.DarkZoneItem;
import net.mcreator.doz_in_maincraft.item.DarkCrystalItem;
import net.mcreator.doz_in_maincraft.item.CylinderWithCompressedAirItem;
import net.mcreator.doz_in_maincraft.item.CopperSwordItem;
import net.mcreator.doz_in_maincraft.item.CopperShovelItem;
import net.mcreator.doz_in_maincraft.item.CopperPickaxeItem;
import net.mcreator.doz_in_maincraft.item.CopperIngotItem;
import net.mcreator.doz_in_maincraft.item.CopperHoeItem;
import net.mcreator.doz_in_maincraft.item.CopperAxeItem;
import net.mcreator.doz_in_maincraft.item.CopperArmorItem;
import net.mcreator.doz_in_maincraft.item.CoolingMechanismItem;
import net.mcreator.doz_in_maincraft.item.ClipTTItem;
import net.mcreator.doz_in_maincraft.item.ClipSWDItem;
import net.mcreator.doz_in_maincraft.item.ClipBisonItem;
import net.mcreator.doz_in_maincraft.item.Clip3Item;
import net.mcreator.doz_in_maincraft.item.Clip2Item;
import net.mcreator.doz_in_maincraft.item.Clip1Item;
import net.mcreator.doz_in_maincraft.item.ChugunItem;
import net.mcreator.doz_in_maincraft.item.CastingMoldItem;
import net.mcreator.doz_in_maincraft.item.CaseShootingRange4Item;
import net.mcreator.doz_in_maincraft.item.CaseShootingRange3Item;
import net.mcreator.doz_in_maincraft.item.CaseShootingRange2Item;
import net.mcreator.doz_in_maincraft.item.CaseShootingRange1Item;
import net.mcreator.doz_in_maincraft.item.Caliber12Item;
import net.mcreator.doz_in_maincraft.item.BoxDetailItem;
import net.mcreator.doz_in_maincraft.item.BowForestersItem;
import net.mcreator.doz_in_maincraft.item.BoltsItem;
import net.mcreator.doz_in_maincraft.item.BloodyTearItem;
import net.mcreator.doz_in_maincraft.item.BatteryItem;
import net.mcreator.doz_in_maincraft.item.AverageHouseholdBoxItem;
import net.mcreator.doz_in_maincraft.item.ArmorFortressItem;
import net.mcreator.doz_in_maincraft.item.AluminumSwordItem;
import net.mcreator.doz_in_maincraft.item.AluminumShovelItem;
import net.mcreator.doz_in_maincraft.item.AluminumPlateItem;
import net.mcreator.doz_in_maincraft.item.AluminumPickaxeItem;
import net.mcreator.doz_in_maincraft.item.AluminumIngotItem;
import net.mcreator.doz_in_maincraft.item.AluminumHoeItem;
import net.mcreator.doz_in_maincraft.item.AluminumAxeItem;
import net.mcreator.doz_in_maincraft.item.AluminumArmorItem;
import net.mcreator.doz_in_maincraft.item.Ak47fullItem;
import net.mcreator.doz_in_maincraft.item.Ak47ammoItem;
import net.mcreator.doz_in_maincraft.item.AddedAromaticSpicesItem;
import net.mcreator.doz_in_maincraft.item.AK47Item;
import net.mcreator.doz_in_maincraft.DozInMaincraftMod;

public class DozInMaincraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, DozInMaincraftMod.MODID);
	public static final RegistryObject<Item> STIMULATOR = REGISTRY.register("stimulator", () -> new StimulatorItem());
	public static final RegistryObject<Item> CASTING_MOLD = REGISTRY.register("casting_mold", () -> new CastingMoldItem());
	public static final RegistryObject<Item> FLUEDGLASS_BUCKET = REGISTRY.register("fluedglass_bucket", () -> new FLUEDGLASSItem());
	public static final RegistryObject<Item> CYLINDER_WITH_COMPRESSED_AIR = REGISTRY.register("cylinder_with_compressed_air", () -> new CylinderWithCompressedAirItem());
	public static final RegistryObject<Item> MAGIC_PINE_WOOD = block(DozInMaincraftModBlocks.MAGIC_PINE_WOOD);
	public static final RegistryObject<Item> MAGIC_PINE_LOG = block(DozInMaincraftModBlocks.MAGIC_PINE_LOG);
	public static final RegistryObject<Item> MAGIC_PINE_PLANKS = block(DozInMaincraftModBlocks.MAGIC_PINE_PLANKS);
	public static final RegistryObject<Item> MAGIC_PINE_LEAVES = block(DozInMaincraftModBlocks.MAGIC_PINE_LEAVES);
	public static final RegistryObject<Item> MAGIC_PINE_STAIRS = block(DozInMaincraftModBlocks.MAGIC_PINE_STAIRS);
	public static final RegistryObject<Item> MAGIC_PINE_SLAB = block(DozInMaincraftModBlocks.MAGIC_PINE_SLAB);
	public static final RegistryObject<Item> MAGIC_PINE_FENCE = block(DozInMaincraftModBlocks.MAGIC_PINE_FENCE);
	public static final RegistryObject<Item> MAGIC_PINE_FENCE_GATE = block(DozInMaincraftModBlocks.MAGIC_PINE_FENCE_GATE);
	public static final RegistryObject<Item> MAGIC_PINE_PRESSURE_PLATE = block(DozInMaincraftModBlocks.MAGIC_PINE_PRESSURE_PLATE);
	public static final RegistryObject<Item> MAGIC_PINE_BUTTON = block(DozInMaincraftModBlocks.MAGIC_PINE_BUTTON);
	public static final RegistryObject<Item> UNFINISHED_STIMULANT = REGISTRY.register("unfinished_stimulant", () -> new UnfinishedStimulantItem());
	public static final RegistryObject<Item> EMPTY_STIMULANT = REGISTRY.register("empty_stimulant", () -> new EmptyStimulantItem());
	public static final RegistryObject<Item> HEALING_MIXTURE = REGISTRY.register("healing_mixture", () -> new HealingMixtureItem());
	public static final RegistryObject<Item> FILLER = REGISTRY.register("filler", () -> new FillerItem());
	public static final RegistryObject<Item> SEEDLING_MAGIC_PINE = REGISTRY.register("seedling_magic_pine", () -> new SeedlingMagicPineItem());
	public static final RegistryObject<Item> SEDLING_MAGIC_PINE = block(DozInMaincraftModBlocks.SEDLING_MAGIC_PINE);
	public static final RegistryObject<Item> SDDD = block(DozInMaincraftModBlocks.SDDD);
	public static final RegistryObject<Item> PATRON_10MM = REGISTRY.register("patron_10mm", () -> new Patron10mmItem());
	public static final RegistryObject<Item> FORESTER_HUNTER_SPAWN_EGG = REGISTRY.register("forester_hunter_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FORESTER_HUNTER, -16764007, -16764058, new Item.Properties()));
	public static final RegistryObject<Item> BOX_FORESTERS = block(DozInMaincraftModBlocks.BOX_FORESTERS);
	public static final RegistryObject<Item> FOREST_ROOTS = block(DozInMaincraftModBlocks.FOREST_ROOTS);
	public static final RegistryObject<Item> COPPER_INGOT = REGISTRY.register("copper_ingot", () -> new CopperIngotItem());
	public static final RegistryObject<Item> COPPER_ORE = block(DozInMaincraftModBlocks.COPPER_ORE);
	public static final RegistryObject<Item> COPPER_BLOCK = block(DozInMaincraftModBlocks.COPPER_BLOCK);
	public static final RegistryObject<Item> COPPER_PICKAXE = REGISTRY.register("copper_pickaxe", () -> new CopperPickaxeItem());
	public static final RegistryObject<Item> COPPER_AXE = REGISTRY.register("copper_axe", () -> new CopperAxeItem());
	public static final RegistryObject<Item> COPPER_SWORD = REGISTRY.register("copper_sword", () -> new CopperSwordItem());
	public static final RegistryObject<Item> COPPER_SHOVEL = REGISTRY.register("copper_shovel", () -> new CopperShovelItem());
	public static final RegistryObject<Item> COPPER_HOE = REGISTRY.register("copper_hoe", () -> new CopperHoeItem());
	public static final RegistryObject<Item> COPPER_ARMOR_HELMET = REGISTRY.register("copper_armor_helmet", () -> new CopperArmorItem.Helmet());
	public static final RegistryObject<Item> COPPER_ARMOR_CHESTPLATE = REGISTRY.register("copper_armor_chestplate", () -> new CopperArmorItem.Chestplate());
	public static final RegistryObject<Item> COPPER_ARMOR_LEGGINGS = REGISTRY.register("copper_armor_leggings", () -> new CopperArmorItem.Leggings());
	public static final RegistryObject<Item> COPPER_ARMOR_BOOTS = REGISTRY.register("copper_armor_boots", () -> new CopperArmorItem.Boots());
	public static final RegistryObject<Item> ALUMINUM_INGOT = REGISTRY.register("aluminum_ingot", () -> new AluminumIngotItem());
	public static final RegistryObject<Item> ALUMINUM_ORE = block(DozInMaincraftModBlocks.ALUMINUM_ORE);
	public static final RegistryObject<Item> ALUMINUM_BLOCK = block(DozInMaincraftModBlocks.ALUMINUM_BLOCK);
	public static final RegistryObject<Item> ALUMINUM_PICKAXE = REGISTRY.register("aluminum_pickaxe", () -> new AluminumPickaxeItem());
	public static final RegistryObject<Item> ALUMINUM_AXE = REGISTRY.register("aluminum_axe", () -> new AluminumAxeItem());
	public static final RegistryObject<Item> ALUMINUM_SWORD = REGISTRY.register("aluminum_sword", () -> new AluminumSwordItem());
	public static final RegistryObject<Item> ALUMINUM_SHOVEL = REGISTRY.register("aluminum_shovel", () -> new AluminumShovelItem());
	public static final RegistryObject<Item> ALUMINUM_HOE = REGISTRY.register("aluminum_hoe", () -> new AluminumHoeItem());
	public static final RegistryObject<Item> ALUMINUM_ARMOR_HELMET = REGISTRY.register("aluminum_armor_helmet", () -> new AluminumArmorItem.Helmet());
	public static final RegistryObject<Item> ALUMINUM_ARMOR_CHESTPLATE = REGISTRY.register("aluminum_armor_chestplate", () -> new AluminumArmorItem.Chestplate());
	public static final RegistryObject<Item> ALUMINUM_ARMOR_LEGGINGS = REGISTRY.register("aluminum_armor_leggings", () -> new AluminumArmorItem.Leggings());
	public static final RegistryObject<Item> ALUMINUM_ARMOR_BOOTS = REGISTRY.register("aluminum_armor_boots", () -> new AluminumArmorItem.Boots());
	public static final RegistryObject<Item> LEAD_INGOT = REGISTRY.register("lead_ingot", () -> new LeadIngotItem());
	public static final RegistryObject<Item> LEAD_ORE = block(DozInMaincraftModBlocks.LEAD_ORE);
	public static final RegistryObject<Item> LEAD_BLOCK = block(DozInMaincraftModBlocks.LEAD_BLOCK);
	public static final RegistryObject<Item> BOX_FORESTERS_OPEN = block(DozInMaincraftModBlocks.BOX_FORESTERS_OPEN);
	public static final RegistryObject<Item> TIN_INGOT = REGISTRY.register("tin_ingot", () -> new TinIngotItem());
	public static final RegistryObject<Item> TIN_ORE = block(DozInMaincraftModBlocks.TIN_ORE);
	public static final RegistryObject<Item> TIN_BLOCK = block(DozInMaincraftModBlocks.TIN_BLOCK);
	public static final RegistryObject<Item> PICKLOCK = REGISTRY.register("picklock", () -> new PicklockItem());
	public static final RegistryObject<Item> PIECE_TIN = REGISTRY.register("piece_tin", () -> new PieceTinItem());
	public static final RegistryObject<Item> ELECTRICAL_TAPE = REGISTRY.register("electrical_tape", () -> new ElectricalTapeItem());
	public static final RegistryObject<Item> ADDED_AROMATIC_SPICES = REGISTRY.register("added_aromatic_spices", () -> new AddedAromaticSpicesItem());
	public static final RegistryObject<Item> LOAD_FORESTERS = REGISTRY.register("load_foresters", () -> new LoadForestersItem());
	public static final RegistryObject<Item> COOLING_MECHANISM = REGISTRY.register("cooling_mechanism", () -> new CoolingMechanismItem());
	public static final RegistryObject<Item> STEAL_INGOT = REGISTRY.register("steal_ingot", () -> new StealIngotItem());
	public static final RegistryObject<Item> STEAL_BLOCK = block(DozInMaincraftModBlocks.STEAL_BLOCK);
	public static final RegistryObject<Item> STEAL_PICKAXE = REGISTRY.register("steal_pickaxe", () -> new StealPickaxeItem());
	public static final RegistryObject<Item> STEAL_AXE = REGISTRY.register("steal_axe", () -> new StealAxeItem());
	public static final RegistryObject<Item> STEAL_SWORD = REGISTRY.register("steal_sword", () -> new StealSwordItem());
	public static final RegistryObject<Item> STEAL_SHOVEL = REGISTRY.register("steal_shovel", () -> new StealShovelItem());
	public static final RegistryObject<Item> STEAL_HOE = REGISTRY.register("steal_hoe", () -> new StealHoeItem());
	public static final RegistryObject<Item> STEAL_ARMOR_HELMET = REGISTRY.register("steal_armor_helmet", () -> new StealArmorItem.Helmet());
	public static final RegistryObject<Item> STEAL_ARMOR_CHESTPLATE = REGISTRY.register("steal_armor_chestplate", () -> new StealArmorItem.Chestplate());
	public static final RegistryObject<Item> STEAL_ARMOR_LEGGINGS = REGISTRY.register("steal_armor_leggings", () -> new StealArmorItem.Leggings());
	public static final RegistryObject<Item> STEAL_ARMOR_BOOTS = REGISTRY.register("steal_armor_boots", () -> new StealArmorItem.Boots());
	public static final RegistryObject<Item> REVOLVER_DRUM = REGISTRY.register("revolver_drum", () -> new RevolverDrumItem());
	public static final RegistryObject<Item> STEEL_BARREL = REGISTRY.register("steel_barrel", () -> new SteelBarrelItem());
	public static final RegistryObject<Item> MOLTEN_STEEL_BUCKET = REGISTRY.register("molten_steel_bucket", () -> new MoltenSteelItem());
	public static final RegistryObject<Item> DRUM_SHAPE = REGISTRY.register("drum_shape", () -> new DrumShapeItem());
	public static final RegistryObject<Item> PRESSURE_REGULATOR = REGISTRY.register("pressure_regulator", () -> new PressureRegulatorItem());
	public static final RegistryObject<Item> ARC_FURNACE = block(DozInMaincraftModBlocks.ARC_FURNACE);
	public static final RegistryObject<Item> GAS = REGISTRY.register("gas", () -> new GasItem());
	public static final RegistryObject<Item> FORRSTER_HUNTER_2_SPAWN_EGG = REGISTRY.register("forrster_hunter_2_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FORRSTER_HUNTER_2, -16764007, -16764058, new Item.Properties()));
	public static final RegistryObject<Item> FORRESTER_HUNTER_3_SPAWN_EGG = REGISTRY.register("forrester_hunter_3_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FORRESTER_HUNTER_3, -16764007, -16764058, new Item.Properties()));
	public static final RegistryObject<Item> FORESTER_HUNTER_4_SPAWN_EGG = REGISTRY.register("forester_hunter_4_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FORESTER_HUNTER_4, -16764007, -16764058, new Item.Properties()));
	public static final RegistryObject<Item> FORESTERS_SPEAR = REGISTRY.register("foresters_spear", () -> new ForestersSpearItem());
	public static final RegistryObject<Item> FORESTER_HUNTER_5_SPAWN_EGG = REGISTRY.register("forester_hunter_5_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FORESTER_HUNTER_5, -16764007, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> EMPTY_BALLOON = REGISTRY.register("empty_balloon", () -> new EmptyBalloonItem());
	public static final RegistryObject<Item> ALUMINUM_PLATE = REGISTRY.register("aluminum_plate", () -> new AluminumPlateItem());
	public static final RegistryObject<Item> NEZERITE_DUST = REGISTRY.register("nezerite_dust", () -> new NezeriteDustItem());
	public static final RegistryObject<Item> NEZERITE_ORE = block(DozInMaincraftModBlocks.NEZERITE_ORE);
	public static final RegistryObject<Item> METAL_FORMING_MACHINE = block(DozInMaincraftModBlocks.METAL_FORMING_MACHINE);
	public static final RegistryObject<Item> EXECUTIONER_HEART = REGISTRY.register("executioner_heart", () -> new ExecutionerHeartItem());
	public static final RegistryObject<Item> GAS_MASK_HELMET = REGISTRY.register("gas_mask_helmet", () -> new GasgasMaskItem.Helmet());
	public static final RegistryObject<Item> GAS_MASK_CRAHET_HELMET = REGISTRY.register("gas_mask_crahet_helmet", () -> new GasMaskCrahetItem.Helmet());
	public static final RegistryObject<Item> GAS_FILTER = REGISTRY.register("gas_filter", () -> new GasFilterItem());
	public static final RegistryObject<Item> TOLKACH = REGISTRY.register("tolkach", () -> new TolkachItem());
	public static final RegistryObject<Item> CLIP_BISON = REGISTRY.register("clip_bison", () -> new ClipBisonItem());
	public static final RegistryObject<Item> GRENADE_40_MM = REGISTRY.register("grenade_40_mm", () -> new Grenade40MmItem());
	public static final RegistryObject<Item> BEAST_FOREST_SPAWN_EGG = REGISTRY.register("beast_forest_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BEAST_FOREST, -13434829, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> BEAST_FOREST_4_SPAWN_EGG = REGISTRY.register("beast_forest_4_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BEAST_FOREST_4, -13434829, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> BEAST_FOREST_3_SPAWN_EGG = REGISTRY.register("beast_forest_3_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BEAST_FOREST_3, -13434829, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> BEAST_FOREST_2_SPAWN_EGG = REGISTRY.register("beast_forest_2_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BEAST_FOREST_2, -13434829, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> BEAST_FOREST_1_SPAWN_EGG = REGISTRY.register("beast_forest_1_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BEAST_FOREST_1, -13434829, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> BEAST_SUMMON_BLOCK = block(DozInMaincraftModBlocks.BEAST_SUMMON_BLOCK);
	public static final RegistryObject<Item> HOZMAG_BRICK = block(DozInMaincraftModBlocks.HOZMAG_BRICK);
	public static final RegistryObject<Item> CLIP_TT = REGISTRY.register("clip_tt", () -> new ClipTTItem());
	public static final RegistryObject<Item> CLIP_SWD = REGISTRY.register("clip_swd", () -> new ClipSWDItem());
	public static final RegistryObject<Item> CALIBER_12 = REGISTRY.register("caliber_12", () -> new Caliber12Item());
	public static final RegistryObject<Item> GHOUL_BANDIT_SPAWN_EGG = REGISTRY.register("ghoul_bandit_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.GHOUL_BANDIT, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> GHOUL_BULL_SPAWN_EGG = REGISTRY.register("ghoul_bull_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.GHOUL_BULL, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> BRIGADIER_GHUL_SPAWN_EGG = REGISTRY.register("brigadier_ghul_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BRIGADIER_GHUL, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> GHOUL_ARROWS_SPAWN_EGG = REGISTRY.register("ghoul_arrows_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.GHOUL_ARROWS, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> GHOUL_RAIDER_SPAWN_EGG = REGISTRY.register("ghoul_raider_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.GHOUL_RAIDER, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> BURNT_BLOOD_HOLE_BLOCK = block(DozInMaincraftModBlocks.BURNT_BLOOD_HOLE_BLOCK);
	public static final RegistryObject<Item> BLOOD_HOLE_BLOCK = block(DozInMaincraftModBlocks.BLOOD_HOLE_BLOCK);
	public static final RegistryObject<Item> BURNT_BLOODY_HOLE = block(DozInMaincraftModBlocks.BURNT_BLOODY_HOLE);
	public static final RegistryObject<Item> BLOODY_HOLE = block(DozInMaincraftModBlocks.BLOODY_HOLE);
	public static final RegistryObject<Item> FIRST_EXECUTIONER_SPAWN_EGG = REGISTRY.register("first_executioner_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FIRST_EXECUTIONER, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> FIRST_EXECUTIONER_2_SPAWN_EGG = REGISTRY.register("first_executioner_2_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FIRST_EXECUTIONER_2, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> FIRST_EXECUTIONER_1_SPAWN_EGG = REGISTRY.register("first_executioner_1_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.FIRST_EXECUTIONER_1, -10092544, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> RISING_EXECUTIONER_SPAWN_EGG = REGISTRY.register("rising_executioner_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.RISING_EXECUTIONER, -13434880, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> PALACH_PR = block(DozInMaincraftModBlocks.PALACH_PR);
	public static final RegistryObject<Item> BLOODY_CLAW_SPAWN_EGG = REGISTRY.register("bloody_claw_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BLOODY_CLAW, -13421773, -13421824, new Item.Properties()));
	public static final RegistryObject<Item> BLOODY_CARCASS_SPAWN_EGG = REGISTRY.register("bloody_carcass_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.BLOODY_CARCASS, -16777216, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> DOUBLE_BLOODY_TEAR = REGISTRY.register("double_bloody_tear", () -> new DoubleBloodyTearItem());
	public static final RegistryObject<Item> TRIPLE_TEAR_BLOOD = REGISTRY.register("triple_tear_blood", () -> new TripleTearBloodItem());
	public static final RegistryObject<Item> BLOODY_TEAR = REGISTRY.register("bloody_tear", () -> new BloodyTearItem());
	public static final RegistryObject<Item> SYMBIOTIC_PIECES = REGISTRY.register("symbiotic_pieces", () -> new SymbioticPiecesItem());
	public static final RegistryObject<Item> SYMBIOTIC_ULCER = REGISTRY.register("symbiotic_ulcer", () -> new SymbioticUlcerItem());
	public static final RegistryObject<Item> BOX_LEVEL_2 = block(DozInMaincraftModBlocks.BOX_LEVEL_2);
	public static final RegistryObject<Item> BOX_LEVEL_3 = block(DozInMaincraftModBlocks.BOX_LEVEL_3);
	public static final RegistryObject<Item> BOX_LEVEL_4 = block(DozInMaincraftModBlocks.BOX_LEVEL_4);
	public static final RegistryObject<Item> CASE_SHOOTING_RANGE_1 = REGISTRY.register("case_shooting_range_1", () -> new CaseShootingRange1Item());
	public static final RegistryObject<Item> CASE_SHOOTING_RANGE_2 = REGISTRY.register("case_shooting_range_2", () -> new CaseShootingRange2Item());
	public static final RegistryObject<Item> CASE_SHOOTING_RANGE_3 = REGISTRY.register("case_shooting_range_3", () -> new CaseShootingRange3Item());
	public static final RegistryObject<Item> CASE_SHOOTING_RANGE_4 = REGISTRY.register("case_shooting_range_4", () -> new CaseShootingRange4Item());
	public static final RegistryObject<Item> BOLTS = REGISTRY.register("bolts", () -> new BoltsItem());
	public static final RegistryObject<Item> BOX_DETAIL = REGISTRY.register("box_detail", () -> new BoxDetailItem());
	public static final RegistryObject<Item> IRON_PLATES = REGISTRY.register("iron_plates", () -> new IronPlatesItem());
	public static final RegistryObject<Item> STEEL_PLATE = REGISTRY.register("steel_plate", () -> new SteelPlateItem());
	public static final RegistryObject<Item> PLATE_SHAPE = REGISTRY.register("plate_shape", () -> new PlateShapeItem());
	public static final RegistryObject<Item> POLKA_1 = block(DozInMaincraftModBlocks.POLKA_1);
	public static final RegistryObject<Item> POLKA_2 = block(DozInMaincraftModBlocks.POLKA_2);
	public static final RegistryObject<Item> POLKA_3 = block(DozInMaincraftModBlocks.POLKA_3);
	public static final RegistryObject<Item> POLKA_4 = block(DozInMaincraftModBlocks.POLKA_4);
	public static final RegistryObject<Item> BLOODY_MOSS = block(DozInMaincraftModBlocks.BLOODY_MOSS);
	public static final RegistryObject<Item> FWW = REGISTRY.register("fww", () -> new FwwItem());
	public static final RegistryObject<Item> DETAIL_PM = REGISTRY.register("detail_pm", () -> new DetailPMItem());
	public static final RegistryObject<Item> DETAIL_SWD = REGISTRY.register("detail_swd", () -> new DetailSWDItem());
	public static final RegistryObject<Item> DETAIL_AKM = REGISTRY.register("detail_akm", () -> new DetailAKMItem());
	public static final RegistryObject<Item> DETAIL_PP_19 = REGISTRY.register("detail_pp_19", () -> new DetailPP19Item());
	public static final RegistryObject<Item> ENGINEERING_WORKBENCH = block(DozInMaincraftModBlocks.ENGINEERING_WORKBENCH);
	public static final RegistryObject<Item> DETAIL_GAUS = REGISTRY.register("detail_gaus", () -> new DetailGausItem());
	public static final RegistryObject<Item> KARBON = REGISTRY.register("karbon", () -> new KarbonItem());
	public static final RegistryObject<Item> DETAIL_SPECIAL_AKM = REGISTRY.register("detail_special_akm", () -> new DetailSpecialAKMItem());
	public static final RegistryObject<Item> BATTERY = REGISTRY.register("battery", () -> new BatteryItem());
	public static final RegistryObject<Item> PLASMA_CABLE = REGISTRY.register("plasma_cable", () -> new PlasmaCableItem());
	public static final RegistryObject<Item> PRECISION_TOOL = REGISTRY.register("precision_tool", () -> new PrecisionToolItem());
	public static final RegistryObject<Item> DETAIL_PPH = REGISTRY.register("detail_pph", () -> new DetailPPHItem());
	public static final RegistryObject<Item> DETAIL_SPAS_12 = REGISTRY.register("detail_spas_12", () -> new DetailSpas12Item());
	public static final RegistryObject<Item> DETAIL_SKAR_H = REGISTRY.register("detail_skar_h", () -> new DetailSkarHItem());
	public static final RegistryObject<Item> AVERAGE_HOUSEHOLD_BOX = REGISTRY.register("average_household_box", () -> new AverageHouseholdBoxItem());
	public static final RegistryObject<Item> LARGE_BOX_FROM_HOZMAG = REGISTRY.register("large_box_from_hozmag", () -> new LargeBoxFromHozmagItem());
	public static final RegistryObject<Item> HUGE_BOX_FROM_HOZMAG = REGISTRY.register("huge_box_from_hozmag", () -> new HugeBoxFromHozmagItem());
	public static final RegistryObject<Item> WEAPON_WORKBENCH = block(DozInMaincraftModBlocks.WEAPON_WORKBENCH);
	public static final RegistryObject<Item> CHUGUN = REGISTRY.register("chugun", () -> new ChugunItem());
	public static final RegistryObject<Item> CRYSTALLINE_WOOD = block(DozInMaincraftModBlocks.CRYSTALLINE_WOOD);
	public static final RegistryObject<Item> CRYSTALLINE_LOG = block(DozInMaincraftModBlocks.CRYSTALLINE_LOG);
	public static final RegistryObject<Item> CRYSTALLINE_PLANKS = block(DozInMaincraftModBlocks.CRYSTALLINE_PLANKS);
	public static final RegistryObject<Item> CRYSTALLINE_LEAVES = block(DozInMaincraftModBlocks.CRYSTALLINE_LEAVES);
	public static final RegistryObject<Item> CRYSTALLINE_SLAB = block(DozInMaincraftModBlocks.CRYSTALLINE_SLAB);
	public static final RegistryObject<Item> CRYSTALLINE_FENCE = block(DozInMaincraftModBlocks.CRYSTALLINE_FENCE);
	public static final RegistryObject<Item> CRYSTALLINE_FENCE_GATE = block(DozInMaincraftModBlocks.CRYSTALLINE_FENCE_GATE);
	public static final RegistryObject<Item> CRYSTALLINE_PRESSURE_PLATE = block(DozInMaincraftModBlocks.CRYSTALLINE_PRESSURE_PLATE);
	public static final RegistryObject<Item> CRYSTALLINE_BUTTON = block(DozInMaincraftModBlocks.CRYSTALLINE_BUTTON);
	public static final RegistryObject<Item> CRYSTAL_GROUND = block(DozInMaincraftModBlocks.CRYSTAL_GROUND);
	public static final RegistryObject<Item> CRYSTAL_STONE = block(DozInMaincraftModBlocks.CRYSTAL_STONE);
	public static final RegistryObject<Item> CRYSTAL_COBBLESTONE = block(DozInMaincraftModBlocks.CRYSTAL_COBBLESTONE);
	public static final RegistryObject<Item> CRYSTAL_EARTH = block(DozInMaincraftModBlocks.CRYSTAL_EARTH);
	public static final RegistryObject<Item> DARK_ZONE = REGISTRY.register("dark_zone", () -> new DarkZoneItem());
	public static final RegistryObject<Item> ENERGY_FRAMEWORK = block(DozInMaincraftModBlocks.ENERGY_FRAMEWORK);
	public static final RegistryObject<Item> CREATIVE_CELL = block(DozInMaincraftModBlocks.CREATIVE_CELL);
	public static final RegistryObject<Item> AMMUNITION_PRESS = block(DozInMaincraftModBlocks.AMMUNITION_PRESS);
	public static final RegistryObject<Item> PILE_CAST_IRON = block(DozInMaincraftModBlocks.PILE_CAST_IRON);
	public static final RegistryObject<Item> CHUGUNN_BLOCK = block(DozInMaincraftModBlocks.CHUGUNN_BLOCK);
	public static final RegistryObject<Item> STABILIZER_STOKER = REGISTRY.register("stabilizer_stoker", () -> new StabilizerStokerItem());
	public static final RegistryObject<Item> STABILIZER_GEMINI = REGISTRY.register("stabilizer_gemini", () -> new StabilizerGeminiItem());
	public static final RegistryObject<Item> STABILIZER_DIODE = REGISTRY.register("stabilizer_diode", () -> new StabilizerDiodeItem());
	public static final RegistryObject<Item> P_762ATRON = REGISTRY.register("p_762atron", () -> new P762atronItem());
	public static final RegistryObject<Item> CLIP_1 = REGISTRY.register("clip_1", () -> new Clip1Item());
	public static final RegistryObject<Item> CLIP_2 = REGISTRY.register("clip_2", () -> new Clip2Item());
	public static final RegistryObject<Item> CLIP_3 = REGISTRY.register("clip_3", () -> new Clip3Item());
	public static final RegistryObject<Item> ARMOR_FORTRESS_HELMET = REGISTRY.register("armor_fortress_helmet", () -> new ArmorFortressItem.Helmet());
	public static final RegistryObject<Item> ARMOR_FORTRESS_CHESTPLATE = REGISTRY.register("armor_fortress_chestplate", () -> new ArmorFortressItem.Chestplate());
	public static final RegistryObject<Item> ARMOR_FORTRESS_LEGGINGS = REGISTRY.register("armor_fortress_leggings", () -> new ArmorFortressItem.Leggings());
	public static final RegistryObject<Item> ARMOR_FORTRESS_BOOTS = REGISTRY.register("armor_fortress_boots", () -> new ArmorFortressItem.Boots());
	public static final RegistryObject<Item> FORTRESS_ARMOR_SET = REGISTRY.register("fortress_armor_set", () -> new FortressArmorSetItem());
	public static final RegistryObject<Item> ARMORERS_WORKBENCH = block(DozInMaincraftModBlocks.ARMORERS_WORKBENCH);
	public static final RegistryObject<Item> SURVIVORS_ARMOR_HELMET = REGISTRY.register("survivors_armor_helmet", () -> new SurvivorsArmorItem.Helmet());
	public static final RegistryObject<Item> SURVIVORS_ARMOR_CHESTPLATE = REGISTRY.register("survivors_armor_chestplate", () -> new SurvivorsArmorItem.Chestplate());
	public static final RegistryObject<Item> SURVIVORS_ARMOR_LEGGINGS = REGISTRY.register("survivors_armor_leggings", () -> new SurvivorsArmorItem.Leggings());
	public static final RegistryObject<Item> SURVIVORS_ARMOR_BOOTS = REGISTRY.register("survivors_armor_boots", () -> new SurvivorsArmorItem.Boots());
	public static final RegistryObject<Item> SURVIVOR_ARMOR_SET = REGISTRY.register("survivor_armor_set", () -> new SurvivorArmorSetItem());
	public static final RegistryObject<Item> OBJECT_STOKER_SPAWN_EGG = REGISTRY.register("object_stoker_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.OBJECT_STOKER, -13434880, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> STOCER = block(DozInMaincraftModBlocks.STOCER);
	public static final RegistryObject<Item> AUTO_MINER = block(DozInMaincraftModBlocks.AUTO_MINER);
	public static final RegistryObject<Item> BET = block(DozInMaincraftModBlocks.BET);
	public static final RegistryObject<Item> SEKRET_ARMOR_HELMET = REGISTRY.register("sekret_armor_helmet", () -> new SekretArmorItem.Helmet());
	public static final RegistryObject<Item> SEKRET_ARMOR_CHESTPLATE = REGISTRY.register("sekret_armor_chestplate", () -> new SekretArmorItem.Chestplate());
	public static final RegistryObject<Item> SEKRET_ARMOR_LEGGINGS = REGISTRY.register("sekret_armor_leggings", () -> new SekretArmorItem.Leggings());
	public static final RegistryObject<Item> SEKRET_ARMOR_BOOTS = REGISTRY.register("sekret_armor_boots", () -> new SekretArmorItem.Boots());
	public static final RegistryObject<Item> KEVLAR = REGISTRY.register("kevlar", () -> new KevlarItem());
	public static final RegistryObject<Item> TITANIUM_PLATES = REGISTRY.register("titanium_plates", () -> new TitaniumPlatesItem());
	public static final RegistryObject<Item> DRON_SPAWN_EGG = REGISTRY.register("dron_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.DRON, -11513776, -11513776, new Item.Properties()));
	public static final RegistryObject<Item> RESCUE_BEACON = REGISTRY.register("rescue_beacon", () -> new RescueBeaconItem());
	public static final RegistryObject<Item> AIRDROP = block(DozInMaincraftModBlocks.AIRDROP);
	public static final RegistryObject<Item> AIRDROP_OPEN = block(DozInMaincraftModBlocks.AIRDROP_OPEN);
	public static final RegistryObject<Item> NYLON_FABRIC = REGISTRY.register("nylon_fabric", () -> new NylonFabricItem());
	public static final RegistryObject<Item> OBJECT_DIODE_SPAWN_EGG = REGISTRY.register("object_diode_spawn_egg", () -> new ForgeSpawnEggItem(DozInMaincraftModEntities.OBJECT_DIODE, -16777165, -16777165, new Item.Properties()));
	public static final RegistryObject<Item> DARK_ZONE_CRYSTAL = block(DozInMaincraftModBlocks.DARK_ZONE_CRYSTAL);
	public static final RegistryObject<Item> DARK_CRYSTAL = REGISTRY.register("dark_crystal", () -> new DarkCrystalItem());
	public static final RegistryObject<Item> SPECIAL_FORCES_COMMUNICATOR = REGISTRY.register("special_forces_communicator", () -> new SpecialForcesCommunicatorItem());
	public static final RegistryObject<Item> BOW_FORESTERS = REGISTRY.register("bow_foresters", () -> new BowForestersItem());
	public static final RegistryObject<Item> L_96_A_1 = REGISTRY.register("l_96_a_1", () -> new L96A1Item());
	public static final RegistryObject<Item> MGL = REGISTRY.register("mgl", () -> new MGLItem());
	public static final RegistryObject<Item> MAGNUM = REGISTRY.register("magnum", () -> new MagnumItem());
	public static final RegistryObject<Item> PP_19_BIZON = REGISTRY.register("pp_19_bizon", () -> new PP19BizonItem());
	public static final RegistryObject<Item> TT = REGISTRY.register("tt", () -> new TTItem());
	public static final RegistryObject<Item> TT_SIMBIOT = REGISTRY.register("tt_simbiot", () -> new TTSimbiotItem());
	public static final RegistryObject<Item> SPAS_12 = REGISTRY.register("spas_12", () -> new SPAS12Item());
	public static final RegistryObject<Item> LAMP = block(DozInMaincraftModBlocks.LAMP);
	public static final RegistryObject<Item> REFUELING_INSTALLATION = block(DozInMaincraftModBlocks.REFUELING_INSTALLATION);
	public static final RegistryObject<Item> FIRST_AID_KIT = block(DozInMaincraftModBlocks.FIRST_AID_KIT);
	public static final RegistryObject<Item> ELECTRICAL_ANOMALY = block(DozInMaincraftModBlocks.ELECTRICAL_ANOMALY);
	public static final RegistryObject<Item> AK_47 = REGISTRY.register("ak_47", () -> new AK47Item());
	public static final RegistryObject<Item> AK_47AMMO = REGISTRY.register("ak_47ammo", () -> new Ak47ammoItem());
	public static final RegistryObject<Item> AK_47FULL = REGISTRY.register("ak_47full", () -> new Ak47fullItem());
	public static final RegistryObject<Item> SCAR_H = REGISTRY.register("scar_h", () -> new ScarHItem());
	public static final RegistryObject<Item> SCAR_H_AMMO = REGISTRY.register("scar_h_ammo", () -> new ScarHAmmoItem());
	public static final RegistryObject<Item> SCAR_HFULL = REGISTRY.register("scar_hfull", () -> new ScarHfullItem());
	public static final RegistryObject<Item> PATRON_556 = REGISTRY.register("patron_556", () -> new Patron556Item());
	public static final RegistryObject<Item> FIRST_AID_KIT_OPPEN = block(DozInMaincraftModBlocks.FIRST_AID_KIT_OPPEN);
	public static final RegistryObject<Item> DFGD = REGISTRY.register("dfgd", () -> new DfgdItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
